apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
- github.com/GoogleCloudPlatform/anthos-service-mesh-samples/docs/ingress-gateway-asm-manifests/with-authorization-policies?ref=asm-acm-tutorial