apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../deploy-policies
patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: onlineboutique
        labels:
          istio.io/rev: asm-managed