apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: onlineboutique
resources:
- github.com/GoogleCloudPlatform/anthos-service-mesh-samples/demos/online-boutique-asm-manifests/base/all?ref=asm-acm-tutorial
components:
- github.com/GoogleCloudPlatform/anthos-service-mesh-samples/demos/online-boutique-asm-manifests/base/for-ingress-gateway?ref=asm-acm-tutorial
patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Namespace
  metadata:
    name: onlineboutique
  $patch: delete