apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  annotations:
    description: "In the ASM root namespace, there should be a default deny AuthorizationPolicy."
  name: defaultdenyauthorizationpolicies
spec:
  crd:
    spec:
      names:
        kind: DefaultDenyAuthorizationPolicies
      validation:
        legacySchema: true
        openAPIV3Schema: {}
  targets:
  - rego: |-
      package asm.security.authorizationpolicy
      violation[{"msg": msg}] {
        is_asm_authz_policy_default_deny(input.review.kind)
        # use input root namespace or default value istio-system
        root_ns := object.get(object.get(input, "parameters", {}), "rootNamespace", "istio-system")
        not namespace_has_default_deny_policy(root_ns)
        msg := sprintf("Root namespace <%v> does not have a default deny AuthorizationPolicy", [root_ns])
      }
      is_asm_authz_policy_default_deny(kind) {
        kind.kind == "DefaultDenyAuthorizationPolicies"
        kind.group == "constraints.gatekeeper.sh"
      }
      namespace_has_default_deny_policy(ns) {
        ap := data.inventory.namespace[ns][_].AuthorizationPolicy[_]
        is_allow_action(ap)
        not ap.spec.rules
      }
      is_allow_action(ap) {
        ap.spec.action == "ALLOW"
      }
      is_allow_action(ap) {
        not ap.spec.action
      }
    target: admission.k8s.gatekeeper.sh