apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PodSidecarInjectionAnnotation
metadata:
  name: pod-sidecar-injection-annotation
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Pod