apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patchesJson6902:
- target:
    kind: AuthorizationPolicy
    name: adservice
  patch: |-
    - op: replace
      path: /spec/rules/0/from/0/source/principals
      value:
        - cluster.local/ns/onlineboutique/sa/frontend
- target:
    kind: AuthorizationPolicy
    name: cartservice
  patch: |-
    - op: replace
      path: /spec/rules/0/from/0/source/principals
      value:
        - cluster.local/ns/onlineboutique/sa/frontend
        - cluster.local/ns/onlineboutique/sa/checkoutservice
- target:
    kind: AuthorizationPolicy
    name: checkoutservice
  patch: |-
    - op: replace
      path: /spec/rules/0/from/0/source/principals
      value:
        - cluster.local/ns/onlineboutique/sa/frontend
- target:
    kind: AuthorizationPolicy
    name: currencyservice
  patch: |-
    - op: replace
      path: /spec/rules/0/from/0/source/principals
      value:
        - cluster.local/ns/onlineboutique/sa/frontend
        - cluster.local/ns/onlineboutique/sa/checkoutservice
- target:
    kind: AuthorizationPolicy
    name: emailservice
  patch: |-
    - op: replace
      path: /spec/rules/0/from/0/source/principals
      value:
        - cluster.local/ns/onlineboutique/sa/checkoutservice
- target:
    kind: AuthorizationPolicy
    name: paymentservice
  patch: |-
    - op: replace
      path: /spec/rules/0/from/0/source/principals
      value:
        - cluster.local/ns/onlineboutique/sa/checkoutservice
- target:
    kind: AuthorizationPolicy
    name: productcatalogservice
  patch: |-
    - op: replace
      path: /spec/rules/0/from/0/source/principals
      value:
        - cluster.local/ns/onlineboutique/sa/frontend
        - cluster.local/ns/onlineboutique/sa/checkoutservice
        - cluster.local/ns/onlineboutique/sa/recommendationservice
- target:
    kind: AuthorizationPolicy
    name: recommendationservice
  patch: |-
    - op: replace
      path: /spec/rules/0/from/0/source/principals
      value:
        - cluster.local/ns/onlineboutique/sa/frontend
- target:
    kind: AuthorizationPolicy
    name: redis-cart
  patch: |-
    - op: replace
      path: /spec/rules/0/from/0/source/principals
      value:
        - cluster.local/ns/onlineboutique/sa/cartservice
- target:
    kind: AuthorizationPolicy
    name: shippingservice
  patch: |-
    - op: replace
      path: /spec/rules/0/from/0/source/principals
      value:
        - cluster.local/ns/onlineboutique/sa/frontend
        - cluster.local/ns/onlineboutique/sa/checkoutservice